internal:
  auth:
    base-url: ${DOMAIN_URL}:${AUTH_PORT}
    register-business-user-credential: /auth/register
  file:
    base-url: ${DOMAIN_URL}:${FILE_PORT}
    upload-file-url: /files
    get-file-info-url: /files/%s/info
  user:
    base-url: ${DOMAIN_URL}:${USER_PORT}
    get-user-info-url: /users/%s/info
  universe:
    base-url: ${DOMAIN_URL}:${UNIVERSE_PORT}