spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
    url: jdbc:mysql://${MYSQL_DB_ADDRESS}:${MYSQL_DB_PORT}/${MYSQL_DB_SCHEME}?serverTimezone=${MYSQL_DB_TIMEZONE}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${JPA_DB_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${JPA_DB_SHOW_SQL}
        format_sql: ${JPA_DB_FORMAT_SQL}
        default_batch_fetch_size: ${JPA_DB_DEFAULT_BATCH_FETCH_SIZE}