spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    url: jdbc:mysql://${AUTH_DB_ADDRESS}:${AUTH_DB_PORT}/${AUTH_DB_SCHEME}?serverTimezone=${AUTH_DB_TIMEZONE}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
      naming:
        physical-strategy: com.hoo.auth.adapter.out.persistence.config.HibernateCustomNamingStrategy
    properties:
      hibernate:
        show_sql: ${DB_SHOW_SQL}
        format_sql: ${DB_FORMAT_SQL}
        default_batch_fetch_size: ${DB_DEFAULT_BATCH_FETCH_SIZE}