storage:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  part-size: ${MINIO_PART_SIZE}
  public-url-expire-min: ${MINIO_PUBLIC_URL_EXPIRE_MIN}
  private-url-expire-min: ${MINIO_PRIVATE_URL_EXPIRE_MIN}