internal:
  gateway:
    base-url: ${INTERNAL_DOMAIN_URL}:${INTERNAL_GATEWAY_PORT}
  auth:
    base-url: ${INTERNAL_DOMAIN_URL}:${INTERNAL_AUTH_PORT}
    register-business-user-credential: /auth/register
  file:
    base-url: ${INTERNAL_DOMAIN_URL}:${INTERNAL_FILE_PORT}
    upload-file-url: /files
    get-file-info-url: /files/%s/info
  user:
    base-url: ${INTERNAL_DOMAIN_URL}:${INTERNAL_USER_PORT}
    get-user-info-url: /users/%s/info
  universe:
    base-url: ${INTERNAL_DOMAIN_URL}:${INTERNAL_UNIVERSE_PORT}